### PR TITLE
Add Initial Content

### PR DESCRIPTION
**Pull request by blink1073**
Brings in the three source files, but they still need to be converted properly to TypeScript.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Wow this is pretty cool Steve.

**Comment by blink1073** [comment]
Okay this is at a point where I am going to start testing it locally from https://github.com/jupyter/jupyterlab/pull/814.  Once it is in a working state we can merge and release.

**Comment by blink1073** [comment]
And thanks for the encouragement, @rgbkrk and @willingc!

**Comment by blink1073** [comment]
Current status: the page loads using these files from https://github.com/jupyter/jupyterlab/pull/814.  I'd say we merge, release 0.1, and iterate.

**Comment by blink1073** [comment]
Cancel that, the page was loading old code, working on fixing.

**Comment by blink1073** [comment]
Okay, now the page loads.

**Comment by jasongrout** [comment]
Let me know when you're ready for review and merge...

**Comment by blink1073** [comment]
Ready now.

**Comment by jasongrout** [comment]
Great. Merging and iterating...

**Pull request merged**
